server:
  port: ${PORT:8082}

spring:
  application:
      name: ${SPRING_APPLICATION_NAME:powerup-service}
      version: ${APP_VERSION:1.0.0}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/powerup}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # MongoDB configuration for traceability
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://davidgarciae_db_user:Rzakn5E7qdkXWu4k@powerup-traceability-de.ukuxpvx.mongodb.net/?retryWrites=true&w=majority&appName=powerup-traceability-dev}
      database: ${MONGODB_DATABASE:powerup-traceability-dev}
      username: ${MONGODB_USERNAME:davidgarciae_db_user}
      password: ${MONGODB_PASSWORD:Rzakn5E7qdkXWu4k}
      # Additional settings for MongoDB Atlas compatibility
      auto-index-creation: true

management:
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

# Microservices URLs (Feign/Integrations)
microservices:
  users:
    url: ${MICROSERVICES_USERS_URL:http://localhost:8081}
  orders:
    url: ${MICROSERVICES_ORDERS_URL:http://localhost:8082}
  messaging:
    url: ${MICROSERVICES_MESSAGING_URL:http://localhost:8083}
  restaurants:
    url: ${MICROSERVICES_RESTAURANTS_URL:http://localhost:8084}

feign:
  clients:
    users-service:
      url: ${MICROSERVICES_USERS_URL:http://localhost:8081}
    messaging-service:
      url: ${MICROSERVICES_MESSAGING_URL:http://localhost:8083}

jwt:
  secret: ${JWT_SECRET:mi-secreto-super-seguro-para-jwt-en-todos-los-servicios-2024}
  expiration: ${JWT_EXPIRATION:86400000}
